### ISSUE TITLE
Extra space when logging in as RLY-0016-3

### ISSUE THREAD

**Issue by Lujke9** [thomotron/sfp-login-page#1]
When I try to log in as RLY-0016-3 "Rolly", there is an extra space in between 'Welcome' and 'Rolly'

**Comment by thomotron** [comment]
Ah, that's probably an issue with the alert trying to show ranks since Rolly doesn't have one. I'll give it a look.

**Comment by thomotron** [comment]
Yeah, it's from the `string.format()` [here](https://github.com/thomotron/sfp-login-page/blob/master/index.js#L43)
